### ISSUE TITLE
Turn off opengl during this process, then turn it back on once the Options > Chart area is left

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#12]
When the database gets updated during the proccess all folders under "charts" directories are scanned weather or not they are listed in the Directories, this takes awhile, then it appears that the opengl cache is updated. (this is a basic opengl feature).  However when there are many charts that are not in the directory, and the charts in the directory start getting fairly large, it appears that opengl updating the cache overpowers the computer when "Apply" or "Close" this process. 

I found the solution was to turn off Opengl during chart changes and file and database updates.

**Comment by nohal** [comment]
If at all valid, this is an issue in OpenCPN core and not in this plugin.

**Comment by rgleason** [comment]
I've been working with Opengl off during this process, and can certainly turn it off when doing charts.
I might try turning it back on to see if there is a problem now.   Yes, it could be a core problem.
