### ISSUE TITLE
Enable use of user created and standard chart subdirectories which support download and catalog

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#14]
At present we are restricted to a single depth (one directory below) format, otherwise the catalogs do not show and downloads do not work.  See this description of the problem.
http://www.cruisersforum.com/forums/f134/chart-downloader-updater-plugin-58737-4.html#post1729188
#58, 59, & 60

Read catalogs from and download to the directory which the chartdownload tool is being pointed at.

**Comment by nohal** [comment]
Sorry, I don't understand at all  - the catalog is read exactly from the directory where the settings point... Of course, it can't be "any" XML file, but exactly the one expected. Why? Because you can point several chart source to the same place. Why? Because it is exactly the result of "I downloaded the whole NOAA portfolio and now want this plugin to manage it" - IMO the standard procedure for a more experienced user.
If your thinking is different or I missed something, please explain better.

**Comment by rgleason** [comment]
Pavel,

I  "Add"ed a new catalog (say region 08), then (not knowing there was an 
associated new path already defined)  went into the destination Browser 
and from "C:/"
clicked through several directories to get to "Data-Dart"
  and  then right clicked and picked  "New Folder" and made a region 
folder "Noaa08"
Then selected that folder. It says (Please Update first)
Then hit Update to get the catalog.
It comes up blank, all the time....  --I guess I did something wrong.
However I always have to reset the base chart directory 
"C:/.../Data-Dart/BSB_ROOT"
or even "C:/../Data-Dart"    for {Chart}

I think I still have to mess with more it to understand.

# This is probably much easier than I am making it!

I did make a subdirectory for a region "../Data-Dart/BSB_ROOT/32region"  
manually and the Update for Catalog did work properly and I could 
download to the the directory...!!!

So its working if you create the subdir manually!

Would like to have the path set to the main Charts directory.

Got to hit the hay, so to speak.
Can do a some more tomorrow.

**Comment by nohal** [comment]
Fixed in 00d47ab96b44d8bb9b5ecdf2fa3159458b2baca4

**Comment by rgleason** [comment]
After fresh install of newly compiled plugin, my the Source headers destination path appeared to be changed to be ...\charts\bsb_root\   for example rather than ..\charts\bsb-root\02region  as I have normally done.  

Nevertheless these Sources with newly configured destination work as configured with charts landing at ..\charts\bsb_root.

Tried "Edit" and changing the destination to  ..\charts\bsb-root\02region  and it does not work as well. When I do the first "Update" the charts are nicely listed, and selection and download will work. However the Source header does not seem to list the XML.  Not sure why,  It exists  here
  ..\charts\bsb-root\02region\02Region_RNCProdCat.xml

There were some other strange things that happened when trying to use this sub sub directory, but I am unable to repeat at the moment. Need some more experience.

How to re-open?

**Comment by nohal** [comment]
By clicking on the Reopen button
what do the ".." mean? Are you using relative paths or just don't want to post the whole thing?

**Comment by rgleason** [comment]
I just tried to shorten the whole pathname  in my description.

Thinking about it...
Maybe there is a Main Chart Path : C:/Data-Dart/Charts 
     Which is shown somewhere and is understood.
Then you could show just the last part of the path?
--- Just an idea.

**Comment by nohal** [comment]
And if I have half my charts in "C:\some charts" and other in "F:\the charts from my bro"? Then I show what? I'm afraid that the "least common denominator" logic is not going to make this thing more usable and understandable.

**Comment by rgleason** [comment]
Agreed.  I think that path idea was a bad idea.
I have been using this for awhile now downloading etc and the xml files are showing up ok now. Perhaps I was seeing a beginning/startup problem with a new version of the plugin.  It think this can be closed again.
