### ISSUE TITLE
Set preffered main chart directory under Preferences.

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#15]
To be able to set the preferred main chart directory under Preferences when in Options > Plugin > Preferences. This would not be forgotten, and would get the user to the top of the Chart directory.

**Comment by nohal** [comment]
Already prepared for it, check https://github.com/nohal/chartdldr_pi/blob/master/src/chartdldr_pi.h#L48 and onwards
The default for {USERDATA} will be GetpPrivateApplicationDataLocation()
The default for {Charts} will be "Charts", of course with an option not to use it

**Comment by rgleason** [comment]
Got it, that might be better.
|{USERDATA}/{Charts}/ENC/US_REGION34|\
Thanks

I was talking about the first part {Charts}
for example my charts are at C:/../Data-Dart/
does not seem to get remembered, and so I thought we should have a way 
to set the {chart}
via Option > Plugins > Preferences.
That is probably what you are planning.

I like that idea of having a regions directory already attached.

**Comment by nohal** [comment]
Rick...
Is something wrong with my English? Or is something not clear on the fact that an Issue which is not closed is not yet implemented?
Or am I just missing what does not seem to get remembered? I'm getting a bit lost here.

**Comment by rgleason** [comment]
Pavel,

I don't mean to mess you up or anything. Just trying to establish what 
is happening in the program and what needs to be done. I am still 
learning it, & testing it.  It is a little late here an I need to stop 
perhaps and work on it more tomorrow.

I can refrain from my comments if that would be better.

Sorry, if I am not helping.

Nite.
Rick

**Comment by nohal** [comment]
Fixed in 00d47ab96b44d8bb9b5ecdf2fa3159458b2baca4
