### ISSUE TITLE
Switch to pugixml

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#2]
For size and speed

**Comment by rgleason** [comment]
git cloned, tried standalone compile, had error of course related to   LINK : fatal error LNK1104: cannot open file '../buildwin/curllib.lib' [C:\Data-Dart\Up-Soft\Navigation\o-plugin\chartdldr_pi\build\chartdldr_pi.vcxproj]

Looked into it. Found that with Weatherfax_pi Pavel has fixed that such that person compiling for Windows (only) had to download wf_depends.7z from Sourceforge opencpnplugins
http://sourceforge.net/directory/os:windows/freshness:recently-updated/?q=wf_depends

Expanded it and put the dlls into the 'buildwin' directory.  Compile normally then works well, including cpack.

**Comment by rgleason** [comment]
Looks like a very nice easy plugin.  I tried to download, and was able to select a couple of charts, and then select "download" and after a long pause, Opencpn crashed and sent a report. This happened twice.

One other thing I noticed was the destination path is not remembered which is a bit of a pain.

**Comment by nohal** [comment]
Rick...
This is a prototype code, 3 years old, definitely NOT ready for any testing...
And this issue is about replacement of tinyxml with pugixml ;)

Pavel

**Comment by rgleason** [comment]
Sure, just thought I'd let you know what I needed to do.
Don't know pugixml, I guess it is Mac.

**Comment by nohal** [comment]
If there still is an issue with the current plugin version integrated in OpenCPN, please open it for OpenCPN, this repository is going to be switched to archive mode.
