### ISSUE TITLE
Fix HTTPS on Windows

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#20]

**Comment by rgleason** [comment]
This is for Brazilain Charts for example.
Just NOW:   o-plugin\chartdldr_pi>git pull      updating 0f35ed1..a8d699e
Brazil RNC  "Update" Catalog 
     "Failed to Download"
     "https://raw.githubusercontent.com/chartcatalogs/catalogs/master/BR_RNC_Catalog.xml"
    "Verify there is a working internet connection."

```
 Tried turning off Norton firewall, no improvement.
```

**Comment by nohal** [comment]
Are you sure you installed the CA certificate bundle as described in the commit closing this issue?

**Comment by rgleason** [comment]
Nope I did not. Yikes there's a lot to keep up with. I saw that will go back.

**Comment by rgleason** [comment]
I see this   in CMakeLists.txt    INSTALL(FILES "buildwin/curl-ca-bundle.crt" DESTINATION ".")
Readme
+Windows, CA certificates bundle 
http://sourceforge.net/projects/opencpnplugins/files/chartdldr_pi/curl-ca-bundle.crt/download 

install  the cert in buildwin

Compiled, still having troubles with  Brazilian RNC, when I define a new source line with Brazilian RNC and hit Update, the source  line disappears.

Should I make a new Issue for Windows?

**Comment by nohal** [comment]
Did you build also after https://github.com/nohal/chartdldr_pi/commit/486e99e0f9eb2f72e9fb66fd9fb7930a9c7f9f1f ?
Have a look at the chart catalog file - if it is ~11kB and unreadable in a text editor, then your problem is already fixed.

**Comment by rgleason** [comment]
Readable I think  222kb     -- should I download again?
GTE CyberTrust Global Root

-----BEGIN CERTIFICATE-----
MIICWjCCAcMCAg ....

**Comment by nohal** [comment]
Rick...
Sorry if I was not clear enough. Not the CA certificate bundle you install with the plugin is what you have to check, but the chart catalog for Brasil you download using the plugin - **BR_RNC_Catalog.xml** in the chart directory

**Comment by rgleason** [comment]
Yes BR_RNC_Catalog.xml is there, 11kb
Chart\BSB_ROOT\Brasil

I guess it is just not seen for some reason, the chart list selection does not come up.

**Comment by nohal** [comment]
OK, then you did not build the fix I mentioned...

**Comment by rgleason** [comment]
Went to bed, no excuse. Did git clone and started over. It works much better!  More magic. Thank you. Both the Brasil and IENC are working for me now. I like the "Show Local Files". More later.
