### ISSUE TITLE
Catalogs  Section  Add  - New Chart Source  -Need it wider to see selection in dropdown

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#26]
Catalog section - Radio button Predefined  ---> Dropdown  selection needs to be wider.

**Comment by rgleason** [comment]
The new Edit function also needs to be wider I think.
-Catalog
-Name
-URL
-Chart Directory
would benefit by being wider too.

**Comment by nohal** [comment]
Rick...
Are you talking about before or after https://github.com/nohal/chartdldr_pi/commit/ab3dd607325357526f74fda24ec47bf2ec29b91d ?
As you sure see, it is the same dialog in both cases.

**Comment by rgleason** [comment]
Yes still the same situation. See 
 Size of chart source definition dialog #39 
Closing this one as it covers same issue.

**Comment by nohal** [comment]
Why did we open that duplicate issue?

**Comment by rgleason** [comment]
Sorry, tried to make it clearer.  A mistake.
