### ISSUE TITLE
Ability to identify which file(s) & directory is used for a certain chart - go to that dir/file

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#29]
Downloaded all of Brazil to test it.
There are about 13 charts that keep coming up with "Update Available" even when "Download"  at least 3 to 4  times.  Some of them are:
- Costa E Ihas Ao Largo (1)
- Costa Nordeste da America do sul (10)
- Ilha da Trindade (21)
- Costa Sueste da America do Sul (30)
- Porto de Barra dos Coqueiros (1001)
- Porto de Salvador (1102)
- De Natal Ao Rio Itarriri (Int 2005)
- Do Arquipelago dos Abrolhos Ao Cabo Frio

I wanted to see the directory and file name  in order to check if there is the necessary folder and file in the proper place, and to try to determine why the status did not change to "Up to Date"

Some way of doing this would be useful.  Perhaps add something to allow:
1. highlight the  particular Chart under "Charts"
2. Right click, and select something like "Show local directory and file"  for the chart.
3. Or maybe some way to see the full path for the chart?

**Comment by nohal** [comment]
Rick, are you sure you are using 0.5 beta?

**Comment by rgleason** [comment]
Will git pull and try again.  No I don't think so because you've commited since this morning (I will guess)

**Comment by nohal** [comment]
Rick...
Please, try the released version, so we are on some common baseline at least once...

**Comment by nohal** [comment]
I suppose we can close this as
- The originating issue with the Brazilian charts is as far as I can tell fixed.
- We by design rely on _some_ chart file in a zip archive having the same name and don't store the file list. And don't want to change it if not needed, which at this point IMO isn't.
- Opening the chart folder is implemented.
  Right?

**Comment by rgleason** [comment]
Initial Brazil problem solved. Yes.  However this request was more about users being able to troubleshoot chart download problems for themselves. 
If they are downloading a certain chart and it does not complete or is a problem in some way, it would be very useful to be able to go to check the files on the local drive.

**Comment by rgleason** [comment]
In case of a failed download, do not display the modal alert #33
but keep downloading charts and display a cumulative information at the end to prevent the process getting stalled because of a problem with one/several files.

The cumulative information would include destination folder and pathnames?

I think this can be closed now.
