### ISSUE TITLE
Restore support for ACE catalogs

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#3]
The Army Corps of Engineers catalogs are currently broken due to a change to file naming (and maybe even format)

**Comment by transmitterdan** [comment]
In chartcatalog.cpp line 96 the string "IENC37ProductCatalog" should be "IENCU37ProductCatalog".

But the bigger problem is that the URL taken from the XML file is actually a redirection. For example this url:

http://ienccloud.us/ienc/web/iencU37productsdownload.cfm?mode=0660&cell=U37AG001

becomes

http://ienccloud.us/ienc/products/files/u37/ienc_s57/U37AG001.zip

after redirection. I don't know how to make wxCurl automatically follow the redirect. For command line curl --location does the trick.

**Comment by nohal** [comment]
We have to set CURLOPT_FOLLOWLOCATION

**Comment by nohal** [comment]
Or just fetch the header in a separate request and behave accordingly, whatever serves better.

**Comment by transmitterdan** [comment]
I could not figure out how to do that. This "hack" makes it all work for now. At ChartCatalog.cpp approximately line 412:

wxString IEncCell::GetChartFilename()
{
      return wxString::Format(_("%s.zip"), name.c_str());
}

wxString IEncCell::GetDownloadLocation()
{
      return wxString::Format(_("http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/products/files/u37/ienc_s57/%s.zip"), name.c_str());
}

It turns out there are multiple redirections that have to be followed. So we really need to figure out how to get the wxCurlDownloadDialog() to follow the redirects and it seems it will all work after that.

**Comment by nohal** [comment]
Does it mean that setting CURLOPT_FOLLOWLOCATION does not work or that you did not figure out how to set it yet? (Wouldn't be surprising as SetOpt is pretty broken in wxCurl)
If it does not work, we basically have two options - read the headers until we get the real URL or ignore it and treat the ACE chart as any other "evil" chart source and implement a mechanism to convert it to the NOAA format including the final URL (which we will have to do for all the non-US chart sources anyway)
The second option would allow us to simplify the code of the plugin, dropping their format, but of course means we have to develop the converter in bash/python/XSLT/whatever running on a unix server...

**Comment by transmitterdan** [comment]
The wxCurlDownloadDialog class does not appear to expose the wxCurl object or provide any method for setting wxCurl options. But I am far from an expert on wx so it may be possible to set options. Google did not turn up any suggestions either.

**Comment by nohal** [comment]
OK, so you did not even try to set it? I understand - it is complicated and actually broken in all of the classes I have ever used (you have to override the functions instead of just setting the options as expected)
To be honest, I'm probably more inclined to dropping the ACE IENC catalog format completely and treating it as for example the Brasilian charts. With the only exception - the input won't be HTML but XML so one part of it will be easier, while the part involving processing several HTTP redirects will be "more complicated".

**Comment by transmitterdan** [comment]
No, I did not try. I will wade through the wx code tonight and see if I can find the right function(s) to override and then try SetOpt(). I'm starting to get a feel for how it can work. My test system works for all charts using the hack I mentioned. I was able to fill up 5GB of disk space in just a little time. 

My view is that ACE can work from their XML without too much hassle. Other countries will be problems as you say. I vote we try New Zealand next if they still have free charts. They did have them not too long ago.

**Comment by nohal** [comment]
NZMariner is good, what they produce not so - they don't publish individual chars but a (yearly?) big file + (weekly or something?) overlay zip file with all the updates.
I will sure start with Brasil and Argentina and then the European IENCs

**Comment by transmitterdan** [comment]
Pavel,

This is where I am as of today. I have a fully functional plugin under Linux Mint that works with ENC< RNC and ACE River charts. Only one file is changed "chartcatalog.cpp". I am still working on the wxCurl problem. I may be close to finding a way to coerce wxDownloadDialog into using redirect but it is fighting back.

diff --git a/src/chartcatalog.cpp b/src/chartcatalog.cpp
index cee0638..59937e2 100644
--- a/src/chartcatalog.cpp
+++ b/src/chartcatalog.cpp
@@ -93,7 +93,7 @@ bool ChartCatalog::LoadFromXml(TiXmlDocument \* doc, bool headerOnly)
                   charts->Add(new EncCell(child));
             }
       }
-      else if (rootName.StartsWith(_T("IENCProductCatalog")))
- ```
   else if (rootName.StartsWith(_T("IENCU37ProductCatalog")))
  ```
  
     {
           if (!ParseNoaaHeader(root->FirstChildElement()))
           {
  @@ -411,12 +411,14 @@ wxString IEncCell::GetChartTitle()
  
  wxString IEncCell::GetChartFilename()
  {
-      return name;
- ```
   return wxString::Format(_("%s.zip"),name.c_str());
  ```
  
  }
  
  wxString IEncCell::GetDownloadLocation()
  {
-      return s57_file->location;
  +//      return s57_file->location;
- ```
   return wxString::Format(_("http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/products/files/u37/ienc_s57/%s.zip"), name.c_
  ```
  
  +
  }
  
  wxDateTime IEncCell::GetUpdateDatetime()

**Comment by transmitterdan** [comment]
Pavel,

I think this should "fix" the redirect problem but it doesn't seem to on my system. Maybe you can try it or figure out the correct way to set the option:

From wxCurlDialog.cpp:

wxCurlDialogReturnFlag wxCurlTransferDialog::RunModal()
{
    m_pThread->GetCurlSession()->SetVerbose(m_bVerbose);
    // Next line should force download to follow redirects. But it doesn't seem to work.
    m_pThread->GetCurlSession()->SetOpt(CURLOPT_FOLLOWLOCATION, 1L);  //TODO: Need to condition this on only HTTP download requests.

**Comment by nohal** [comment]
Dan...
When you post code snippets, please format them as code so they are readable (``` before and after it)
We definitely can't include that AWS address hack in the code, way too fragile.
My suspicion is that the download thread will be broken in a similar way as wxCurlHTTP, where SetCurlHandleToDefaults resets any options you try to set, so it has to be overriden in your own inherited class.

**Comment by transmitterdan** [comment]
Pavel,

I think I found a way to make wxCurl follow the redirects. I would like someone to try this. In src/wxcurl/base.cpp in function

`void wxCurlBase::SetCurlHandleToDefaults(const wxString& relativeURL)`

there are some SetOpt lines like this:

```
        SetOpt(CURLOPT_HEADERFUNCTION, wxcurl_header_func);
        SetOpt(CURLOPT_WRITEHEADER, &m_szResponseHeader);
        SetOpt(CURLOPT_ERRORBUFFER, m_szDetailedErrorBuffer);
        SetOpt(CURLOPT_FOLLOWLOCATION, 1L);   // <--insert this hack
```

What we really need is a new pair of functions in the base class that works like SetVerbose/GetVerbose. They could be SetFollowLocation/GetFollowLocation but I didn't want to mess with the header file  wxCurl.h as it is in the base wxWidgets installation. Then we would need a way to call these from the higher level dialog functions only when HTTP requests are being made.

Thanks for the hint about inserting code.

**Comment by nohal** [comment]
Yes, that's what I thought, thanks for trying.
wx/curl/base.h is not in wxWidgets base, it is in our tree, so we can fix it as we need.

**Comment by transmitterdan** [comment]
I finally tested it and it does download a file but not the right one. I'm pretty close to finding the problem. I think libcurl needs a couple more options besides just FOLLOWLOCATION.

**Comment by transmitterdan** [comment]
Ok, I am stuck. CURLOPT_FOLLOWLOCATION gets lost somehow and doesn't follow all the links. This is what I know from using curl at the command line:

This is what comes out of the XML file. Getting that URL returns header info on the first redirect:

```
chartdldr_pi/build $ curl -i 'http://ienccloud.us/ienc/web/iencU37productsdownload.cfm?mode=660&cell=U37AR376'
HTTP/1.1 301 Moved Permanently
Server: Sun-ONE-Web-Server/6.1
Date: Fri, 23 Jan 2015 17:30:03 GMT
Content-length: 122
Content-type: text/html
Location: http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/web/iencU37productsdownload.cfm?mode=660&cell=U37AR376
Connection: close

<HTML><HEAD><TITLE>Moved Permanently</TITLE></HEAD>
<BODY><H1>Moved Permanently</H1>
An error has occurred.
</BODY></HTML>
```

Then that url returns a redirect header like this:

```
chartdldr_pi/build $ curl -i 'http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/web/iencU37productsdownload.cfm?mode=660&cell=U37AR376'
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
Location: http://ienccloud.us/ienc/products/files/u37/ienc_s57/U37AR376.zip
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Fri, 23 Jan 2015 17:32:46 GMT
Content-Length: 0
```

And finally then another redirect comes back from that url:

```
chartdldr_pi/build $ curl -i 'http://ienccloud.us/ienc/products/files/u37/ienc_s57/U37AR376.zip'
HTTP/1.1 301 Moved Permanently
Server: Sun-ONE-Web-Server/6.1
Date: Fri, 23 Jan 2015 17:42:22 GMT
Content-length: 122
Content-type: text/html
Location: http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/products/files/u37/ienc_s57/U37AR376.zip
Connection: close

<HTML><HEAD><TITLE>Moved Permanently</TITLE></HEAD>
<BODY><H1>Moved Permanently</H1>
An error has occurred.
</BODY></HTML>
```

That final location URL will download by the download dialog class. But I can't figure out how to manually trace through all the intermediate URL's using wxCURL. Maybe someone can take the hints above and fix this permanently. Until then the hack still works.

**Comment by transmitterdan** [comment]
Pavel,

Found another "hack" that works:

This code works in the file wxcurl/base.cpp

```
//////////////////////////////////////////////////////////////////////
// Helper Methods
//////////////////////////////////////////////////////////////////////

void wxCurlBase::SetCurlHandleToDefaults(const wxString& relativeURL)
{
    if (!relativeURL.empty())
        SetURL(relativeURL);        // update the m_szCurrFullURL string

    if(m_pCURL && ResetHandle())
    {
        // Here we manufacture our own headers
        const char *headers = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0\r\n" \
                                "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n" \
                                "Accept-Language: en-US,en;q=0.5\r\n" \
                                "Accept-Encoding: gzip, deflate\r\n" \
                                "Connection: keep-alive";

        ResetResponseVars();

        SetStringOpt(CURLOPT_URL, m_szCurrFullURL);


        SetOpt(CURLOPT_HEADERFUNCTION, wxcurl_header_func);
        SetOpt(CURLOPT_WRITEHEADER, &m_szResponseHeader);
        SetOpt(CURLOPT_ERRORBUFFER, m_szDetailedErrorBuffer);
        SetOpt(CURLOPT_USERAGENT, headers);
        SetOpt(CURLOPT_FOLLOWLOCATION, 1L);
```

The problem is that the server that ACE uses is too smart for its own good. Apparently it looks at the headers and if it thinks this is not a real web browser it redirects to some nonworking URL. You can "trick" wxCURL into using your own headers using the SetOpt(CURLOPT_USERAGENT, string): function. This function merely writes out the text "User-Agent: " followed by the string. So I captured what my web browser writes into the headers and feed that to wxCurl. And now it correctly follows the links and downloads the file.

I have not tried to figure out which of these headers are redundant. Probably some of them are not needed.

**Comment by nohal** [comment]
This looks MUCH better ;)
Many thanks!

**Comment by rgleason** [comment]
Dan looks like you are having fun. It the real location something like this one?
Location: http://ec2-54-235-76-27.compute-1.amazonaws.com/ienc/products/files/u37/ienc_s57/U37AR376.zip

Which looks like a public amazon server.  I wonder if it would let you query directly somehow?
--No get 403 errors

**Comment by transmitterdan** [comment]
Rick,

It works now that I faked a web browser set of headers. The Army server is just a bit too picky about the GET request. But what had me stymied is they redirect to some obscure network solutions URL instead of returning a proper 500 server error. The fix can be tested by Pavel easily. 

Best regards,
Dan Dickey

**Comment by rgleason** [comment]
Dan I am envious, you are able to gain headway on this stuff. Well done.

**Comment by transmitterdan** [comment]
Pavel,

You probably have this figured out but I wanted to leave you with my changes here. I have confirmed that they work on Windows and Linux now as of the git version earlier today. I have no OSX machine for testing. Hopefully someone can verify that it works on OSX too.

Rick, If you make these changes to your Windows sources then the Army river charts should work.

```
diff --git a/src/chartcatalog.cpp b/src/chartcatalog.cpp
index ae1420d..611ca9d 100644
--- a/src/chartcatalog.cpp
+++ b/src/chartcatalog.cpp
@@ -93,7 +93,7 @@ bool ChartCatalog::LoadFromXml(TiXmlDocument * doc, bool headerOnly)
                   charts->Add(new EncCell(child));
             }
       }
-      else if (rootName.StartsWith(_T("IENCProductCatalog")))
+      else if (rootName.StartsWith(_T("IENCU37ProductCatalog")))
       {
             if (!ParseNoaaHeader(root->FirstChildElement()))
             {
@@ -411,7 +411,7 @@ wxString IEncCell::GetChartTitle()

 wxString IEncCell::GetChartFilename()
 {
-      return name;
+   return wxString::Format(_("%s.zip"), name.c_str());
 }

 wxString IEncCell::GetDownloadLocation()
diff --git a/src/wxcurl/base.cpp b/src/wxcurl/base.cpp
index ef0cca7..93fbf2f 100644
--- a/src/wxcurl/base.cpp
+++ b/src/wxcurl/base.cpp
@@ -783,6 +783,13 @@ void wxCurlBase::SetCurlHandleToDefaults(const wxString& relativeURL)

     if(m_pCURL && ResetHandle())
     {
+       // Here we manufacture our own headers
+        const char *headers = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0\r\n" \
+                      "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n" \
+             "Accept-Language: en-US,en;q=0.5\r\n" \
+             "Accept-Encoding: gzip, deflate\r\n" \
+                  "Connection: keep-alive";
+
         ResetResponseVars();

         SetStringOpt(CURLOPT_URL, m_szCurrFullURL);
@@ -790,6 +797,8 @@ void wxCurlBase::SetCurlHandleToDefaults(const wxString& relativeURL)
         SetOpt(CURLOPT_HEADERFUNCTION, wxcurl_header_func);
         SetOpt(CURLOPT_WRITEHEADER, &m_szResponseHeader);
         SetOpt(CURLOPT_ERRORBUFFER, m_szDetailedErrorBuffer);
+        SetOpt(CURLOPT_USERAGENT, headers);
+        SetOpt(CURLOPT_FOLLOWLOCATION, 1L);

         if(m_pEvtHandler && (m_nFlags & wxCURL_SEND_PROGRESS_EVENTS))
         {

```

**Comment by transmitterdan** [comment]
Pavel,

I recommend removing the header line that begins "Accept-Encoding: gzip...".  I think that line may cause problems in the future. 

Best regards,
Dan Dickey

**Comment by rgleason** [comment]
Dan, I put your changes in the diff into the src files and it works! 
The IENC U7 chart list just showed up when I highlighted the chart source without need for "Update" so it was always there from the first download.

**Comment by rgleason** [comment]
Maybe for NZ Charts it could be worked out to just put a Source header for NZ charts with a message (Select Download no chart catalog 134mb)
Same for the update?

**Comment by rgleason** [comment]
It might be good to have a little wider drop down area when selecting sources.

**Comment by rgleason** [comment]
Also in Catalog Title   more informative.
RNC 02 Region RI to Canada
RNC 03 Region NY, Nantckt. to C.May
RNC 04 Chesapeake
RNC 05 Norfolk VA to FL
RNC 06 FL East, Keys
RNC 07 FL West, Keys

## Etc

Region 02 - Block Island, RI to the Canadian Border
Region 03 - New York to Nantucket and Cape May, NJ
Region 04 - Chesapeake and Delaware Bays
Region 06 - Norfolk, VA to Florida including the ICW
Region 07 - Florida East Coast and the Keys
Region 08 - Florida West Coast and the Keys
Region 10 - Puerto Rico and the U.S. Virgin Islands
Region 12 - Southern California: Point Arena to the Mexican Border
Region 13 - Lake Michigan
Region 14 - San Francisco to Cape Flattery
Region 15 - Pacific Northwest: Puget Sound to the Canadian Border
Region 17 - Mobile, AL to the Mexican Border
Region 22 - Lake Superior and Lake Huron (U.S. Waters)
Region 24 - Lake Erie (U.S. Waters)
Region 26 - Lake Ontario (U.S. Waters)
Region 30 - Southeast Alaska
Region 32 - South Central Alaska: Yakutat to Kodiak
Region 34 - Alaska: The Aleutians and Bristol Bay
Region 36 - Alaska: Norton Sound to Beaufort Sea
Region 40 - Hawaiian Islands and U.S. Territories

**Comment by nohal** [comment]
Rick...
Dialog size: New issue, please
NZ: What does it have to do with this issue? Why is this not posted in in #4?
Please, try to understand, we need to keep this a little less messy...

**Comment by nohal** [comment]
Again - Marine ENCs and RNCs - What do they have to do with the ACE catalog?

**Comment by rgleason** [comment]
Sorry Pavel, I will be more careful. I guess this becomes a good tool if we use it right!!!

Just NOW:   o-plugin\chartdldr_pi>git pull      updating 0f35ed1..a8d699e
ACE Inland ENC
      Update works and I can download charts, but the note goes back to  "Please update first"
      If I  "Apply" and then "Ok" to close Options,
      Then go back to Chart Downloader and "Update" ACE the entire chart source disappears
     so it has to be recreated again.
     Closed Opencpn and restarted. Went to Chart Downloader.
     Found ACE Inland source listed again in the list!  Tried "update". It disappeared again.
      After first listing of charts, download, there are problems being able to download again.
