### ISSUE TITLE
Support for large zipped chart areas without Catalog such as NZ

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#30]
A way to select NZ and set a destination directory,
Initiate full download and install without a directory.
Upack and install charts in the destination, 
then create an xml directory from the charts if the zip does not contain one.

**Comment by nohal** [comment]
Rick...
What would the XML created from the directory be good for? There is no way to download individual charts and no way to tell if any individual chart was updated or not.

**Comment by rgleason** [comment]
Probably no use, I guess.  ...So can we get it downloaded and installed in a destination dir?

**Comment by nohal** [comment]
Of course, as soon as we create the catalog file for http://chartcatalogs.github.io/ -> This is part of #4 and I'm closing it.

**Comment by rgleason** [comment]
I think I am a little slow at getting this. I had found  http://chartcatalogs.github.io/  
Now I need to learn how to format the xml, by lookingg at brazil.
 Awesome.
