### ISSUE TITLE
RNC & ENC  shorten & change Source Header descriptions

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#31]
If possible, shorten Source Headers and add descriptive locations.
Saw some of this but it seems to have disappeared.
Tried to shorten and still have it understood.
## Do we need we need "Region"? 

US RNC Region 02 - RI - Canada
US RNC Region 03 - Nantucket - NJ
US RNC Region 04 - Delaware
US RNC Region 06 - VA - FL
US RNC Region 07 - FL East
US RNC Region 08 - FL West
US RNC Region 10 - P.Rico -Virgin I.
US RNC Region 12 - S.CA
US RNC Region 13 - L.Michigan
US RNC Region 14 - S.Fran - C.Flattery
US RNC Region 15 - P.NW - Canada
US RNC Region 17 - AL - Mexico
US RNCRegion 22 - L. Superior & Huron
US RNC Region 24 - L. Erie
US RNC Region 26 - L. Ontario
US RNC Region 30 - AL SE
US RNC Region 32 - AL Central
US RNC Region 34 - AL Aleutians
US RNC Region 36 - AL N.S.- Beauf.
US RNC Region 40 - Hawai

**Comment by nohal** [comment]
I don't know... Do Gringos need region? Do you know the region you are in?
The current values are taken exactly from the NOAA website (http://www.charts.noaa.gov/MCD/images/list.txt) - I thought that is what an American is used to... 
Why should we change it?

**Comment by rgleason** [comment]
Pavel, gringos don't need region, they need to know what they are doing. I am in Region 02  I know that because I know the Coast Guard Regions, but a lot of people would not.  However it is the most efficient way to download. What we need it thee limits of the regions for people. I think.

But if it is just for me,  I can certainly live with it just the way it is!  The downloader is quite convenient as it is.  Maybe someone else has some thoughts on this?

Your Gringo, Rick

**Comment by nohal** [comment]
That's why I would stick with the official names from NOAA - I suppose people should be most familiar with their terminology. If they don't fit into the dropdown on Windows, we will simply make it wider.

**Comment by rgleason** [comment]
Ok
