### ISSUE TITLE
Download of a certain file causes a crash. Uncheck it to continue and download it last.

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#32]
RNC Region 02  -   Monhegan Island to Cape Eliz  
and others caused repeated crash and close of OpenCPN.  
Got over it by uncheck the first problem chart and continue download.
Then it seemed to download at the end after checking it again.

Various charts when downloading force Opencpn to crashes or close, so OpenCPN has to be reopened.
If I uncheck the chart so it can go on. that helps.

**Comment by nohal** [comment]
Can't reproduce, more info needed.
Is it repeatable (= Is there a chart that you can't download at all)?
When exactly the crash happens (halfway during the download, before it starts, when it is finished)?

**Comment by rgleason** [comment]
There are no charts I have found that can't be downloaded yet.

Opencpn closes halfway through large successive downloads at a certain (same) chart.
If I uncheck that chart, the download will continue.
Once completed, I can then often download the problem chart.

I wonder if there is a way to catch the failure somehow, and restart the chart download or some way to skip it.  Perhaps it is some memory problem....for large downloads, just don't know.  How would I check this?  Have 8gb ram.

I can certainly live with this, but there may be some users who have more trouble with it, say if it happens more frequently.

I will try downloads with the new compile and report.

**Comment by rgleason** [comment]
Pavel, I just downloaded Region 04 all at once with no hangups.  Looks like it might be better. Will try some more tomorrow early. 

git branch -v      \* master f4e31f1 Adjust the default column sizes ..fix #27

**Comment by rgleason** [comment]
Pavel, just "Updated" all of  ENC Region 03  with no hangups.

**Comment by rgleason** [comment]
I think we can close this now.
