### ISSUE TITLE
DownloadDialog modality will annoy some users

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#37]
This problem has been reported already in flyspray/tracker. But now it will probably begin to annoy a whole new group of users (i.e. newbies using chartdldr pi). Anytime a modal dialog "pops up", at least on Windows 7, OpenCPN comes to the front. If you have a long download of charts going it is very annoying. Every time the DownloadDialog box pops up to start a new chart download it sends whatever window you were working in behind OpenCPN. Interestingly the focus is still with the window that is behind O. I am pretty sure this is a wxWidgets thing.

**Comment by nohal** [comment]
Me too. And to make it worse, platform dependent... If I had a good solution, this would have been resolved a long time ago for the SENC generation dialog. So far I don't.

**Comment by rgleason** [comment]
I have found this modality issue to be true too.

**Comment by transmitterdan** [comment]
Then may I suggest a solution for this. We might find a way to eliminate the need for these annoying popups altogether. Here are a couple of ideas for thought:

1)  We don't have to use the DownloadDialog for the chart download. It would be sufficient in my view to write into the chart list control where it says new, updated, or up to date that the file is downloading and % progress. The abort and pause buttons could be on the main panel next to the download charts button. Abort and Pause would be grey unless a download was in progress. It would be really cool if the list scrolled up as each chart is downloaded in turn. But that should not cause the O main screen to constantly pop up in front of other tasks.

2) For the SENC case it would be sufficient in my opinion to put a progress indication in the lower information bar (I don't know the correct name but it's where the coordinates, bearing, distance, SOG and COG are displayed). Whilst SENC update is in progress these other parameters aren't meaningful anyway.

**Comment by nohal** [comment]
Yes, all doable. Patches welcome ;)

**Comment by rgleason** [comment]
Would this be fixed if we could minimize the "Downloading...." window?
No, it appears that both the OpenCPN window and Options window pop up to the top after each download completes.  This interrupts use of the computer for other things while downloading. It is a minor inconvenience, but a fix would be welcome at some point.

**Comment by transmitterdan** [comment]
Pavel,

I made a version of the plugin that doesn't pop-up the dialog box for each download. If you are interested I can send you the diff information. Or if not interested just let me know. I am not sure what to do with github to transmit the changes back so you could review them.

Personally I like it but it has a few things I don't have enough knowledge to fix (e.g. I can't get the list box to automatically scroll up to show each chart as it is downloaded). I think it would solve the wxString threadsafe issue if that is truly a problem. It blocks waiting for the download thread to finish.

**Comment by nohal** [comment]
Dan...
It should be as simple as `git push` - I suppose you have your fork set as origin for your local tree, if not, send the output of `git branch -a` and I will give you the exact sequence of commands to use.

**Comment by transmitterdan** [comment]
Pavel - see below:

```
dan@dan-VirtualBox ~/GitOpenCPN/OpenCPN/plugins/chartdldr_pi $ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/coverity_scan
  remotes/origin/master
dan@dan-VirtualBox ~/GitOpenCPN/OpenCPN/plugins/chartdldr_pi $ 
```

Also, I don't understand GetText and POEdit so I did not do anything about translations. I will eventually learn that too.

**Comment by nohal** [comment]
And which github tree `origin` is? Yours or mine? `git remote -v` will tell you
If it is a clone of yours, just do `git commit -a -m "Description of the changes"` and `git push`
If it is a clone of mine, add also yours using `git remote add dan https://github.com/transmitterdan/chartdldr_pi.git`, then the same commit and `git push dan master`

**Comment by nohal** [comment]
gettext not needed to study, you can update the POT template by a simple `make chartdldr-pot-update`, but don't worry about it, we will do it later when the strings settle down.

**Comment by transmitterdan** [comment]
Ok, I think I pushed it all up. I had to merge some changes you had made but it wasn't much change. I think it works now ok at least when I test it on Linux. I will try to test it later tonight on Windows.

**Comment by nohal** [comment]
I get the idea, it is good, but it needs quite a bit more work....
- https://github.com/transmitterdan/chartdldr_pi/compare/nohal:master...master#diff-cacfc6975689f18fcc0b16de3f639460R674 blocks the UI completely, giving the user an impression that the application got stuck (All the way to the OS reporting it unresponsive and asking if it has to be killed) Probably not too apparent when your connection is really fast, but very much so over slower connections like mine (in theory, but just in theory, 10 mbps ADSL).
  It needs a true background thread, which will also mean it can be aborted. We basically have to do the same wxCurlDownloadDialog does regarding the progress reporting and abortion. It also means we will have to react to other user actions (We can disable everything on our own panel, but still the user will be able to simply close the Toolbox...)
- Using wxMessageBoxes to report failures will stop the download until the user reacts - for this reason I did https://github.com/nohal/chartdldr_pi/commit/439e1b196b12407eb0d946ede5e80c07c899c0c4

**Comment by transmitterdan** [comment]
I thought about the error message dialog boxes a bit. I think it's a tossup whether to keep them or not. They call attention to a problem whereas if all goes well nothing much happens.

Yes, I know it needs some non-blocking stuff. Basically just need to release the GUI in a loop waiting for the download complete event would be simple enough. Later we can add progress reporting if we like but I don't think we need it during each chart download.

**Comment by rgleason** [comment]
Download Dialog Modality - Downloading Brazil Charts the dialogue seems to pop up on top, more so when the other application is not full screen.  When downloading other charts this is not so much of a problem (I've downloaded most of them and have not run across it with those charts.)

--PS I can live this this.

**Comment by transmitterdan** [comment]
This issue is insidious. If I put Windows Explorer on top of OpenCPN then usually that will stop the annoying popups from taking focus away from something else. I have no idea why that works. But it probably means the problem is deeper than just wxWidgets and we cannot fix within this plugin.

**Comment by rgleason** [comment]
Transmitter Dan, thank you for trying to fix this one smalll aspect. I think the problem is almost gone and is much much better than before. I would not worry too much about this at this point and suggest closing it?

**Comment by rgleason** [comment]
T Dan, 
Think it is almost fixed.  Modality is broken when a chart download starts, after that it is possible to double click the program you were working in and continue until the next chart starts downloading, and the download window and OpenCPN window pop up to the top.  This only occurs when the chart starts download!   -So it is almost fixed.

**Comment by nohal** [comment]
Implemented in https://github.com/nohal/chartdldr_pi/tree/remove_modal - I'm for now leaving the catalog downloads use the modal dialogs, not that we can't switch them to use the background thread as well.

**Comment by nohal** [comment]
Do we still have some issues here? I would say the Toolbox tab integration made everybody happy?

**Comment by rgleason** [comment]
Its working great Pavel, in my opinion. Thank you.  Did the entire east coast NOAA.
If you'd like I can check a few others.

Checked Bulgaria, Brasil, Poland all worked.

**Comment by transmitterdan** [comment]
Yes, I will close this issue.
