### ISSUE TITLE
Source Headers  - Sort by click on Catalog, Released or Path

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#38]

**Comment by rgleason** [comment]
Pavel, after cleaning up chart directories by manually editing opencpn.ini I have a couple of small requests to make it easier for the user to view edit the chartdowwnloader section of ini file to manually sort the chart downloader file such that when first opened it appears in the native order of the ini file.
1. Each catalog record shown on its own line when you open the ini file in a text editor.
2. I guess this means there would be a carriage return at the end, which is a problem with various OS. Maybe there is some other clever way to handle this. The ChartList section seems to work this way, but I am having some difficulties with manually sorting that too.
3. Maybe when the opencpn.ini is read in the chartdownloader section, the carriage return and any spaces up to the next character would be eliminated during the reading. (I think that is what would need to happen but I am not sure of this.)
4. To edit this section I have to put in a carrage return in the right location ...right after the end of the record  "|"  and then sort it manually.  Then I delete the carriage return and hope for the best. Sometimes I find I've missed or messed up something and have to edit it again.
5. I did have good success initially in editing the chart destination pathnames which helped the cleanup out quite a bit.

Of course it would be very nice to be able to sort by Catalog, Released or Path so that we could more easily compare the Chartdownler  to the ChartList to make sure we have the paths done and correct.

Thanks for a great plugin.
By the way I was using a recently Fetched Version 1.0 branch and compiling for Opencpn v4.0 
I have noticed that I needed to download NZ several times and I am not sure those changes made it into the Ocpnv4.0 version of the the plugin?   I guess use will determine. 

--Will try the new version soon.

**Comment by nohal** [comment]
Rick...
Can you please open new issues for new stuff?

Thanks

Pavel

**Comment by rgleason** [comment]
Sorry, will do.

**Comment by nohal** [comment]
If there still is an issue with the current plugin version integrated in OpenCPN, please open it for OpenCPN, this repository is going to be switched to archive mode.
