### ISSUE TITLE
Add support for other free chart sources

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#4]
It will be necessary to process the charts available and create the catalogs.
Use https://github.com/chartcatalogs/ to accomplish that.

**Comment by rgleason** [comment]
Pavel, I've tried most recent git fetch and IENC and Brazilian do not seem to show up.
See post #78 and Dan's just before there are some screenshots. 
http://www.cruisersforum.com/forums/f134/chart-downloader-updater-plugin-58737-6.html#post1732032

**Comment by rgleason** [comment]
I just made Dan's diff changes and when I just opened the IENC U7 source by highlighting, the list of charts just appeared without any need to hit "Update".   I guess they were always there after the first "Upgade" but not seen?    Brazil still is not loading the chart list.

**Comment by nohal** [comment]
Rick...
"Most recent" is exactly what?

**Comment by rgleason** [comment]
Pavel, I think it was about 3:55pm EST that I git fetched... IENC U7 didn't work then, then I saw Dan's git diff and made the changes and it worked.

**Comment by nohal** [comment]
Rick...
This does not help at all... Before posting comments like this:
1) make sure you have the latest code
2) make sure that there actually was a change that was supposed to fix the issue (git log).
3) post the comment in the relevant issue - in case of brasilian charts catalog download it is #20 
4) Post stuff relevant to the issue you are commenting - this one really has nothing to do with ACE IENCs - #3 is the one related.
I suppose both #3 and #20 were addressed in https://github.com/nohal/chartdldr_pi/commit/66a8f06ba4238345735884ff56f83ef2c9a0e873 and you built an older codebase.

**Comment by rgleason** [comment]
Pave, I am confused. The title says  "Add support for other free chart sources #4"
pretty broad and would cover  IEC U7  and Brazilian.
How recent? -  "3:55pm EST that I git fetched..."  that is pretty recent, did you change it after that?

..\o-plugin\chartdldr_pi>git branch -v
- master 0f35ed1 [behind 4] Add the Brasilian RNC Charts (#4)-
- Was not working for me, nor were the IENC U7 so I changed the files as Dan sugggested.
- I will git pull and try again.
- Sorry if this is of no use.

**Comment by nohal** [comment]
Rick...
We already have support for ACE charts - it was broken and there is a separate issue for it. This issue is to track addition of NEW data sources. If we add it and it is broken, there has to be new issue for it (as in case of the Brasilian charts. The reason for it not working for you was the HTTPS protocol support broken on Windows, absolutely nothing to do with the charts or the catalog)
If we keep mixing everything together, we will never release anything...

**Comment by rgleason** [comment]
Pavel, I don't know all these things....its a bit of a black box you see  :)
1.  I am not going to say HTTPS protocol support on Windows is broken in a new issue, not in scope, however I must say https does work for me in my browser just fine!!!
2.  When there is an issue closed, should it stay closed? -We must add a new issue even if it is the same or similar?

**Comment by nohal** [comment]
Rick...
We are not developing your browser here, are we?
If the issue is closed and the solution does not work as expected, reopen it. If it is a completely different thing, create new issue.

**Comment by rgleason** [comment]
Tried manual download of the two NZ large zips and the failed and were much smalller than listed. Then tried an early version of Chartdlr and it succeeded!

**Comment by nohal** [comment]
I think I'm done with what's available world-wide. And the plugin is part of OpenCPN now.
