### ISSUE TITLE
Chart Area -  Right click  - "Select Updated"  change to "Select Update"

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#41]
I believe "Select Update" is clearer.

**Comment by nohal** [comment]
I don't think so, it does not even sound English to me

**Comment by rgleason** [comment]
Pavel as you know  "updated"  is past tense, In my mind it has been done.

**Comment by nohal** [comment]
Exactly - it means "Select the charts that have been updated by the publisher"

**Comment by rgleason** [comment]
Ok understood, sorry.
