### ISSUE TITLE
Explain the user what to do after adding source/updating charts

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#42]
- When the user adds a chart source, in case it is not already covered by some of GetChartDBDirArrayString(), we have to tell him that he has to add it to the list of chart directories.
- When the user updates charts, we have to tell him to update the chart database

Both of these features will be replaced by #9 and #10 in 2.0

**Comment by rgleason** [comment]
Yes, new users will think they can just use the charts. So our wiki needs to make that clear.

**Comment by rgleason** [comment]
Have put this in the wiki at end of new users. I think this csn be closed.
