### ISSUE TITLE
Brutalize the URL validity checks

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#51]
Implement checks for catalog URL validity, as strict as possible....

**Comment by transmitterdan** [comment]
Pavel, do we want to make a file of "legal" chart catalog URLs and if the user picks one that isn't on our vetted list then they get a warning or something? I don't think we should disallow any URL so long as it is at least a properly formed URL.

**Comment by nohal** [comment]
No, no file, I have enough work without having to maintain another list of something... Just a normal validity check.
