### ISSUE TITLE
Testing for ill formed URL improvement

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#53]
This line:

```
    wxRegEx re(_T("^https?\\://[a-zA-Z0-9\\./_-]*\\.[xX][mM][lL]$") ); //TODO: wxRegEx sucks a bit, this RE is way too naive
```

should eliminate URLs that don't end in .xml.

**Comment by nohal** [comment]
The question is: Are we sure they always will end in .XML? But you are right, reading the "errors" reported, this is less evil... :)

**Comment by transmitterdan** [comment]
Pavel,

I will try to find out why this error happens. I thought I fixed it so that if the catalog was not parsed it did not take on the strings from another chart source. I must have missed something.

**Comment by transmitterdan** [comment]
Pavel,

I built a debug dll from the clone of the latest github sources. With that plugin dll I cannot duplicate the problem reported by Gilletarom. However, when I use the dll from this install (http://sourceforge.net/projects/opencpnplugins/files/chartdldr_pi/chartdldr_pi-0.6-win32.exe/download) the bug reappears. Are you sure the 0.6 .dll has the issue #45 updates? It appears not to have those fixes.

**Comment by nohal** [comment]
Yes, pretty sure, otherwise it could never produce an installer with 0.6 in the name as the version bump commit came later...
Anyway, that stuff needs a bit more love, I don't think that https://github.com/nohal/chartdldr_pi/commit/4ade900eebabfb937e505e7c59f9f9f0a45da258 fixes it at all (I hope I didn't forget to apply some part of it - a pull request would be easier. And I suppose that the issue you talk about is "I've put a total nonsense in the configuration, the loading failed miserably, of course, and still "something else but a proper error message" happened)...
People are torturing our baby in a really unimaginable ways :)

**Comment by transmitterdan** [comment]
Pavel,

The debug version of the dll does not have the problem. The release version does. I don't know how that could happen.

**Comment by transmitterdan** [comment]
Ok, I have it sorted now. I will send you a patch in a bit. The fix is easy.

**Comment by transmitterdan** [comment]
The problem was the invalidating of dates and titles was in the wrong member function. This patch will help Gilletarom I think.

```
diff --git a/src/chartcatalog.cpp b/src/chartcatalog.cpp
index 68f6b12..1cc1da3 100644
--- a/src/chartcatalog.cpp
+++ b/src/chartcatalog.cpp
@@ -39,6 +39,11 @@
 // Chart Catalog implementation
 bool ChartCatalog::LoadFromFile(wxString path, bool headerOnly)
 {
+      dt_valid = wxInvalidDateTime;      // Invalidate all dates
+      date_created = dt_valid;            // so dates of one catalog
+      time_created = dt_valid;            // don't propagate into another
+      date_valid = dt_valid;
+      title = _T("Catalog is not valid.");      // Invalidate the title in case we read a bad file
       if (!wxFileExists(path))
             return false;
       TiXmlDocument * doc = new TiXmlDocument();
@@ -84,11 +89,6 @@ wxDateTime ChartCatalog::GetReleaseDate()
       TiXmlElement * root = doc->RootElement();
       wxString rootName = wxString::FromUTF8( root->Value() );
       charts->Clear();
-        dt_valid = wxInvalidDateTime;      // Invalidate all dates
-        date_created = dt_valid;            // so dates of one catalog
-        time_created = dt_valid;            // don't propagate into another
-        date_valid = dt_valid;
-        title = _T("Title not found.");      // Invalidate the title incase we read a bad file

       if (rootName.StartsWith(_T("RncProductCatalog")))
       {
```
