### ISSUE TITLE
Dialog window placement

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#54]
Make sure dialogs are centered on all platforms (seems they aren't on Windows).

**Comment by rgleason** [comment]
The update dialogues seem to be centered when using windows.
The add catalog, seems to be always to the right, does not have a memory if moved. I can live with iit
The edit catalog  seems to be always to the right and does not have a memory if moved. I can live with this.
Show Local files has a memory for location and height and width which is just fine with me.
