### ISSUE TITLE
Get rid of the "update dance" after deleting a catalog

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#57]
After deleting a catalog we should not allow any events to happen and just clean the form and select nothing.

**Comment by rgleason** [comment]
I have deleted several catalogs and closed Opencpn and opened and have found no update dance that I could identify.

**Comment by transmitterdan** [comment]
It must be that this problem is fixed because when deleting a catalog then no catalog is selected. Can we close this issue?

**Comment by nohal** [comment]
No, we can't the issue is not fixed.

**Comment by rgleason** [comment]
How can I make the dance happen?   Maybe a Linuz issue?

**Comment by nohal** [comment]
Run Linux with Gnome, have a lot of chart sources configured, delete one.

**Comment by transmitterdan** [comment]
Pavel,
I can’t exactly see a huge problem but I did make an attempt to fix this issue. You may please try the fork at github.com/transmitterdan/chartdldr_pi to see if it helps.
It seems the issue might be that under some window managers the wxListCtrl refuses to have no items selected. Under Windows this situation is acceptable to the wxListCtrl. I don’t know if my “fix” will help your issue or not so please let me know.
Thanks,
Dan
