### ISSUE TITLE
Add the possibility to direct the user to manual download

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#58]
German charts are not downloadable automatically and user interaction is required.
Add support for catalogs directing the user to the manual download page instead of downloading the charts.

**Comment by rgleason** [comment]
Yes, I am able to download these pretty easily. I guess it is not possible to have wxcurl download them.
https://www.elwis.de/Service/Inland-ENC-der-WSV/IENC-Dateien/index.php.html

**Comment by rgleason** [comment]
Same issue with the China charts but you need to register with user name and password. Also it appears the 3 version is going to be one where there will be some payment I believe. I have downloaded the 2nd version but have not tried to install yet.
