### ISSUE TITLE
Downloading of Inland IENC ACE charts is broken in 0.7

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#59]
We broke the ACE chart download in 0.7. I am working to find the cause. I think it is simple and hope to send a patch shortly.

**Comment by transmitterdan** [comment]
I forked this repository and fixed the ACE chart download problem. You can see the fix here: https://github.com/transmitterdan/chartdldr_pi/commit/405ff9dabd8b3732bbfe0c240be0e976ee6d3c2f

**Comment by rgleason** [comment]
I am using T Dan version.  It is downloading now. I am just letting it run  IENC  US
