### ISSUE TITLE
Installer names program OpenCPN and version 0.7

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#60]
At least for me on Windows 7 the installer names the program OpenCPN (incorrect) and gives it the version 0.7 (which is correct). It should name it Chartdldr_pi I think. I have looked at the CMake files but can't find why the installer gives it a name of OpenCPN. This is what I see in the Control Panel after installing the downloader plugin.

![image](https://cloud.githubusercontent.com/assets/10525699/6352757/a5a103e0-bc0a-11e4-91ea-1877e7462e11.png)

Does anyone else see this same issue?

**Comment by rgleason** [comment]
I do not seem to have this problem but Logbook Konni shows up as OpenCPN with a version number of 1.2014 I believe.
Attached are two shots.

![screenshot 2015-02-24 11 22 50](https://cloud.githubusercontent.com/assets/2363959/6355435/fca1fce4-bc23-11e4-92b7-666b3d4f66c2.png)

![screenshot 2015-02-24 12 53 42](https://cloud.githubusercontent.com/assets/2363959/6355474/53f936ec-bc24-11e4-8285-bc652f7b6c1d.png)

**Comment by transmitterdan** [comment]
Rick,

In your control panel how is chartdldr_pi shown? Is it called chartdldr_pi? The uninstall executable is a different thing. That is ok. It's the label given to the list of programs that is confusing.

**Comment by rgleason** [comment]
There is no chartdldr appearing under Contrl Panel / Programs
Only Opencpn 3.2.2  and 4.0 and opencpn 1.2014 (logbook konni)

**Comment by transmitterdan** [comment]
That's strange. On my system there is an OpenCPN 0.7 program installed which I know to be Chartdldr_pi.

**Comment by rgleason** [comment]
Dan to be clear..
Have installed Chartdldr from your git 
chartdldr_pi-0.7-0v4.0-p-06e4684-disable-cert-win32.exe   commit  06e4684
In Windows under Uninstall program  lists
OpenCPN  opencpn.org  2/24/2015    Version 0.7
There is a Chartdldr uninstaller in the Opencpn directory too.

PS The line in the Program Uninstaller that had Logbook Konni is now gone.

**Comment by rgleason** [comment]
If Plugins are shown in Program Uninstaller, would be nice if they had
OpenCPN [Version No] [Plugin Name] [Version No]

And that they were all consistant at some point. ---Something to work towards perhaps.
