### ISSUE TITLE
Downloader plugin can "hang" OpenCPN

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#61]
Pavel,

I have found what might be considered a "serious" bug in this plugin. It is possible for a libcurl transfer to get hung and that in turn will hang OpenCPN. The scenario is like this:

1) A download is in progress
2) The connection is broken (e.g. network failure)
3) The libcurl Perform() function never returns. However, it does keep sending events to wxcurl_evt_progress_func()

At present the only way out of this is to kill the OpenCPN task. My view would be this is not acceptable for most users.

I believe the reason this happens is because libcurl does not recover from a lost connection at least on Windows Vista and Windows 7. It may behave differently on Linux or Mac. I don't know if the root cause is a problem with the Windows TCP stack or just that libcurl does not check that the socket connection has become broken. I can find no curl_easy_setopt() code that would seem to affect this scenario directly.

The abort button on the download dialog does not work due to another bug in wxCurl. The code that watches for the Abort flag only checks if the user wants to abort when a chunk of data is received (or uploaded). However, in the scenario above no data will ever be received so the Abort flag is set but never checked thus the download thread is literally hung forever. It keeps making calls to wxcurl_evt_progress_func() though so you can see the data has stopped.

There are 3 possible solutions I can think of.

1) Set a timeout on the libcurl transfer. This is dangerous because we have no way of knowing how long to set the timeout and we might cause problems with slow networks. If we set the timeout too short some people with slow internet may not be able to use the downloader. It might be ok if we make this timeout a plugin parameter set by the user.

2) Set a speed timeout using:
        SetOpt(CURLOPT_LOW_SPEED_TIME, NNL);
        SetOpt(CURLOPT_LOW_SPEED_LIMIT, MMl);

This tells libcurl that if the bytes per second is below MM bytes per second for more than NN seconds then abort the transfer. I tried this and it works. The downside is that if the transfer is almost finished when the network fails it can take a long time (up to an hour) before the bytes per second decays to the MM value.

3) Hack on the wxCurlBase and wxCurlBaseThread objects so that we can abort a hung transfer. This is possible if in the "C" function wxcurl_evt_progress_func() we return 1 instead of 0. According to libcurl documentation that will signal the transfer to end prematurely. In fact, the libcurl documentation recommends that as a better method of handling a timeout situation. I don't know why the original wxCurl writer(s) did not use that as the way to deal with the Abort button.

I am leaning toward doing both #2 and #3 but I really need your input and advice before proceeding. But I am concerned that we will have problems if this isn't fixed somehow. Many boaters are on long distance WiFi and this is when the problem happens. In fact, that's how I found it on my boat.

Thanks,
Dan

**Comment by nohal** [comment]
Dan...
Seems reasonable. I would maybe even use just the third option - hate when SW is trying to be smarter than me...

**Comment by transmitterdan** [comment]
Pavel,

Thanks for quick reply. I have a way mapped out for #3. Will post something later today.

Dan

**Comment by transmitterdan** [comment]
Pavel,

Have this fixed in my fork. I don't know if you are pulling code out of my fork or not. I notice you are closing some issues that are addressed over there. If you need anything let me know.

Dan

**Comment by nohal** [comment]
Dan...
Yes, I'm pulling the commits from your fork. I'm now working on #58 - Once done we should be ready for the last beta.

Many thanks for your efforts

Pavel
