### ISSUE TITLE
Resizing downloader dialog clips off lowest buttons

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#64]
A tiny nuisance was found by Gilletarom. If the "Update All" button is hidden then the vertical slider of the dialog does not allow to expose the bottom row of buttons. The solution is to make the "Update All" button hidden and disabled in wxFormBuilder before generating code. Then the auto size features correctly handle the case when this button is hidden programatically. There is no other effect, the button still can be unhidden and enabled as before.

**Comment by transmitterdan** [comment]
The fix for this seems to leave the "Update All" button in the wrong place under at least Windows XP. See attached screen shot.
![updateallbutton](https://cloud.githubusercontent.com/assets/10525699/7107437/1552411e-e12b-11e4-95e3-cf8e3d7a4d44.png)

**Comment by nohal** [comment]
I suppose it is now fixed in the master

**Comment by transmitterdan** [comment]
Yes, it is fixed now.
From what I can tell you are ready for 1.0 release unless you know something else.
