### ISSUE TITLE
Make handling of invalid catalogs more robust

### ISSUE THREAD

**Issue by nohal** [nohal/chartdldr_pi#67]
With invalid catalog XML, we have to clean the chart list completely and indicate error, not show nonsense.
![screenshot from 2015-05-30 19 50 57](https://cloud.githubusercontent.com/assets/249856/7900024/561dac38-0705-11e5-8860-142d9843df87.png)

**Comment by transmitterdan** [comment]
Patel,

Also, there is some issue with New Zealand latest update zip file. Downloaded thinks it is always out of date. 

Best regards,
Dan Dickey

**Comment by nohal** [comment]
Dan...
Can't reproduce (The May update to the catalog was pushed online about an hour ago and once I download the updated ZIP, everything seems OK)

Pavel

**Comment by nohal** [comment]
There actually was a bug causing the data for the first selected catalog to be overwritten by the local file scan. Fixed in 63c1983f7333a4d22f8c403ca3ab728a710fa494
