### ISSUE TITLE
Context Menu - Move Up or Move Down  (also Chart Directory if possible)

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#68]
Earlier Title:
 Opencpn.ini section - Make with one Catalog record on each line - for ease of edit order #68 

Pavel, after cleaning up chart directories by manually editing opencpn.ini I have a couple of small requests to make it easier for the user to view edit the chartdowwnloader section of ini file to manually sort the chart downloader file such that when first opened it appears in the native order of the ini file.
1. Each catalog record shown on its own line when you open the ini file in a text editor. I guess this means there would be a carriage return at the end, which is a problem with various OS. Maybe there is some other clever way to handle this. The ChartList section seems to work this way, but I am having some difficulties with manually sorting that too.
2. Maybe when the opencpn.ini is read in the chartdownloader section, the carriage return and any spaces up to the next character would be eliminated during the reading. (I think that is what would need to happen but I am not sure of this.)
3. To edit this section I have to put in a carrage return in the right location ...right after the end of the record "|" and then sort it manually. Then I delete the carriage return and hope for the best. Sometimes I find I've missed or messed up something and have to edit it again.

I did have good success initially in editing the chart destination pathnames which helped the cleanup out quite a bit.

Of course it would be very nice to be able to sort by Catalog, Released or Path so that we could more easily compare the Chartdownler to the ChartList to make sure we have the paths done and correct.

Thanks for a great plugin.
By the way I was using a recently Fetched Version 1.0 branch and compiling for Opencpn v4.0
I have noticed that I needed to download NZ several times and I am not sure those changes made it into the Ocpnv4.0 version of the the plugin? I guess use will determine.

--Will try the new version soon.

**Comment by nohal** [comment]
Rick...
I just don't understand one thing - Why do you want to edit the ini file manually? Is there anything that can't be done in the GUI?

**Comment by rgleason** [comment]
Yes,
For me it was easier to change the destination pathnames after I had reorganized my mess of chart files and testing.
Also that is the only way to get my list of catalogs in the same order as the list of chart files so that I can check that I have parallel alignment between the Chart list and Chart Downloader.
Otherwise it is/was a complete mess, dependent on when I added a catalog, etc.

Just easier for me to move the downloaded files with the old catalogs in them into the folder organization I wanted, then edit the opencpn.ini file accordingly.

How would you do this?  Delete and download them all again having set the new destination directory?

**Comment by rgleason** [comment]
Short Answer - In the GUI you can't sort it.  In opencpn.ini I am able to almost sort it (gets pretty close).

**Comment by nohal** [comment]
I would click on the Edit button to change the paths.
Yes, sorting/reordering might be missing from the GUI, I'm just not sure I want to clutter it with more buttons, so maybe a context menu would be better.

**Comment by rgleason** [comment]
Sorry, what do you mean by context menu?
- How does the plugin use the Opencpn.ini section?
- Does it do any sorting?  or is it just read in order?
- Maybe you just have a Right Click 
  -- Sort by Date, 
  -- Sort by Path, 
  -- Sort by Catalog
  -- Order of ini
  along with the other choices?

**Comment by nohal** [comment]
Context menu, in common computer terminology, is what you get on right-click, when applicable. It by itself does nothing, of course, but it can contain actions that make sense in the given context, like "Move up"/ "Move down" on list rows.
Of course the manual reordering is in a little logical conflict with sorting of any kind.
If I ever implement sorting (#38), it will be done by clicking on the column headers.
If I ever implement manual reordering, it will probably be done by using a context menu.

**Comment by rgleason** [comment]
Context Menu Right Click Move Up or down works for me!!!
It would be great if the Chart Directories List did the same thing.
So that the user could get things arranged and sort out what needed to be done, what paths are missing and what catalog.xml files are missing.

It would be a big help.

**Comment by nohal** [comment]
If there still is an issue with the current plugin version integrated in OpenCPN, please open it for OpenCPN, this repository is going to be switched to archive mode.
