### ISSUE TITLE
Crash with latest NOAA RNC chart catalog

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#69]
It appears something in the NOAA RNC chart catalog dated 24.7.2015 is causing the downloader to crash with a null pointer error. I haven't figured out where in the .xml file the problem exists.

**Comment by transmitterdan** [comment]
The file causing the crash is the one for all RNC charts: RNCProdCat.xml

**Comment by nohal** [comment]
We crash in the Chart constructor due to empty zipfile_size for chart 1113A
Easy fix, will commit in a few minutes..

**Comment by transmitterdan** [comment]
Pavel,

It still crashes for me while it is trying to populate the chart list dialog. I deleted the .xml file and downloaded again with same result.

Dan

**Comment by nohal** [comment]
Dan...
Are you sure you pulled and built the last commit https://github.com/nohal/chartdldr_pi/commit/2d6578fe2062fb74710e3132982779352f36eaa5? Which platform are you testing?

Pavel

**Comment by transmitterdan** [comment]
Pavel,
Yes, I pulled and built from last commit.
I am testing under Windows 8.1. The problem appears to be when it tries to parse the XML for chart 540 which is right before 1113A.
Dan

**Comment by transmitterdan** [comment]
I’m sorry did another git pull and it updated one source file. That’s probably the issue.

Dan

**Comment by nohal** [comment]
I hope so, otherwise black magic is involved :)
When unsure what you have locally, have a look at `git log`
