### ISSUE TITLE
Unable to Update / Download Brasil RNC Charts

### ISSUE THREAD

**Issue by Guil27** [nohal/chartdldr_pi#72]
When I try to update / download Brasil RNC charts Chart downloader gives me the following error message: "Failed to Download Catalog: 
https://raw.githubusercontent.com/chartcatalogs/catalogs/master/BR_RNC_Catalog.xml 
Verify there is a working Internet connection."    --- Can you help ? Thanks

![screen shot 2016-07-22 at 2 45 38 am](https://cloud.githubusercontent.com/assets/20591379/17047574/d58892e0-4fb5-11e6-800f-ebcb0566a8d1.png)

**Comment by nohal** [comment]
Try to edit `/Applications/OpenCPN.app/Contents/Info.plist`
adding 

```
        <key>NSAppTransportSecurity</key>
        <dict>
          <key>NSAllowsArbitraryLoads</key><true/>
        </dict>
```
