### ISSUE TITLE
"Select All" Charts  button in the Download Panel

### ISSUE THREAD

**Issue by rgleason** [nohal/chartdldr_pi#74]
Would save time and trouble checking them all.
Great plugin. Love it. Thanks.

PS  Spacebar to check and Arrow down is useful and quicker/easier than mouse click, but  "Select All" next to "Help" would be better.

**Comment by nohal** [comment]
Use the right-click context menu.

**Comment by rgleason** [comment]
Yes! I just read it. Forgot. Sorry.  Was going to close it.
